export const books = [
    {
      id: 1,
      title: "Dune",
      author: "Frank Herbert",
      genre: "Sci-fi",
      description: "A science fiction saga set on the desert planet Arrakis.",
      published: 1965,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDu_5-HXb84QkH9_oMyDcQRo57RvneoN2Sow&s",
      rating:3.5,
    },
    {
      id: 2,
      title: "The Martian",
      author: "Andy Weir",
      genre: "Sci-fi",
      description: "An astronaut stranded on Mars struggles to survive and return to Earth.",
      published: 2011,
      image: "https://m.media-amazon.com/images/I/51QimqeXMXL._AC_UF1000,1000_QL80_.jpg",
      rating:4.2,
    },
    {
      id: 3,
      title: "The Alchemist",
      author: "Paulo Coelho",
      genre: "Fiction",
      description: "A young shepherd travels to Egypt after having a recurring dream about finding treasure.",
      published: 1988,
      image: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
      rating:4.3,
    },
    {
      id: 4,
      title: "Becoming",
      author: "Michelle Obama",
      genre: "Fiction",
      description: "A deeply personal memoir by the former First Lady of the United States.",
      published: 2018,
      image: "https://th.bing.com/th/id/OIP.e__NEYvJpiqMPy4lAR_zHgHaLQ?rs=1&pid=ImgDetMain",
      rating:4.4,
    },
    {
      id: 5,
      title: "Educated",
      author: "Tara Westover",
      genre: "Non-fiction",
      description: "A memoir about a woman who grows up in a strict and abusive household in rural Idaho but eventually escapes to learn about the wider world through education.",
      published: 2018,
      image: "https://rukminim1.flixcart.com/image/300/300/xif0q/book/k/x/u/educated-original-imah39dh9x3h2yg4.jpeg",
      rating:4.6,
    },
    {
      id: 6,
      title: "Harry Potter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      genre: "Fantasy",
      description: "A young wizard's journey begins at Hogwarts School of Witchcraft and Wizardry.",
      published: 1997,
      image: "https://m.media-amazon.com/images/I/81q77Q39nEL.jpg",
      rating:3.9,
    },
    {
      id: 7,
      title: "The Name of the Wind",
      author: "Patrick Rothfuss",
      genre: "Fantasy",
      description: "The autobiography of a gifted young man who grows up to be the most notorious magician his world has ever seen.",
      published: 2007,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPCVd291mQlUEsViqPj66QTJyYSnK5CLiSoA&s",
      rating:4.0,
    }
  ];
  